export enum ErrorMessage {
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  EMAIL_REGISTERED = "EMAIL_REGISTERED",
  SHOP_NOT_REGISTERED = "SHOP_NOT_REGISTERED",
  SHOP_NOT_FOUND = "SHOP_NOT_FOUND",
  KEY_NOT_FOUND = "KEY_NOT_FOUND",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  INVALID_TOKEN = "INVALID_TOKEN",
  NEED_LOGIN_AGAIN = "NEED_LOGIN_AGAIN",

  INVALID_MEMORY_UNIT = "INVALID_MEMORY_UNIT",
  NEGATIVE_MEMORY_VALUE = "NEGATIVE_MEMORY_VALUE",

  INVALID_PRODUCT_TYPE = "INVALID_PRODUCT_TYPE",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_ALREADY_PUBLISHED = "PRODUCT_ALREADY_PUBLISHED",

  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  DISCOUNT_EXISTED = "DISCOUNT_EXISTED",
  DISCOUNT_NOT_FOUND = "DISCOUNT_NOT_FOUND",
  DISCOUNT_USAGE_LIMIT_REACHED = "DISCOUNT_USAGE_LIMIT_REACHED",
  DISCOUNT_EXPIRED = "DISCOUNT_EXPIRED",
  ORDER_NOT_ENOUGH_FOR_DISCOUNT = "ORDER_NOT_ENOUGH_FOR_DISCOUNT",
}
