enum ErrorMessage {
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  EMAIL_REGISTERED = "EMAIL_REGISTERED",
  SHOP_NOT_FOUND = "SHOP_NOT_FOUND",
  KEY_NOT_FOUND = "KEY_NOT_FOUND",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  INVALID_TOKEN = "INVALID_TOKEN",

  INVALID_MEMORY_UNIT = "INVALID_MEMORY_UNIT",
  NEGATIVE_MEMORY_VALUE = "NEGATIVE_MEMORY_VALUE",
}

export { ErrorMessage };
