enum ErrorMessage {
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  EMAIL_REGISTERED = "EMAIL_REGISTERED",

  INVALID_MEMORY_UNIT = "INVALID_MEMORY_UNIT",
  NEGATIVE_MEMORY_VALUE = "NEGATIVE_MEMORY_VALUE",
}

export { ErrorMessage };
